name: CI/CD Pipeline

on:  [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.5"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Test"
        run: "composer test"
        env:
          BGG_AUTH_TOKEN: "${{ secrets.BGG_AUTH_TOKEN }}"
          BGG_USERNAME: "${{ secrets.BGG_USERNAME }}"
          BGG_PASSWORD: "${{ secrets.BGG_PASSWORD }}"
